name: SentinelOps CI - P1

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-test-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install bandit

      - name: Run unit tests
        run: |
          echo "No tests yet"

      - name: Run Bandit SAST
        run: |
          bandit -r . -f json -o bandit-report.json || true

      - name: Build Docker image
        run: |
          docker build -t sentinelops-demo:latest .

      - name: Install Trivy
        run: |
          sudo apt-get update
          sudo apt-get install -y gnupg lsb-release curl
          curl -fsSL https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo gpg --dearmor -o /usr/share/keyrings/trivy.gpg
          echo "deb [signed-by=/usr/share/keyrings/trivy.gpg] https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main" | sudo tee /etc/apt/sources.list.d/trivy.list
          sudo apt update
          sudo apt install trivy -y
      
      - name: Scan Docker image with Trivy
        run: |
          trivy image --format json --output trivy-report.json sentinelops-demo:latest || true

      - name: Run Security Decision Engine
        run: |
          python security_decision_engine.py
